### ISSUE TITLE
No conditional access choice in Enterprise Application created

### ISSUE THREAD

**Issue by nimsim** [signupsoftware/exflowwebd365o#3]
Hi,

When deploying the script, there is no option for conditional access in the Enterprise App created in Azure AD. Is there a way to manually add this?

**Comment by nimsim** [comment]
Hi again,

Haven't been able to test, but it seems you need to add the tag "WindowsAzureActiveDirectoryIntegratedApp" on New-AzureADServicePrincipal
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadserviceprincipal?view=azureadps-2.0

Although it does not state that Conditional Access is bound to Tags, this is what gave us the option to add Conditional Access on the app. 

Set-AzureADServicePrincipal -ObjectId xx -Tags WindowsAzureActiveDirectoryIntegratedApp

**Comment by PierreGode** [comment]
Solved
